### ISSUE TITLE
Not working on nova v2.0.9

### ISSUE THREAD

**Issue by onemoreahmad** [DigitalCloud/nova-custom-views#21]
Hello,
Thanks for awesome package!

I just upgrade nova from 2.0.6 to 2.0.9.
Old views don't work anymore and when I create a new view from the command line I got an error saying:
 "**Module build failed: TypeError: this.setDynamic is not a function**"

**Comment by onemoreahmad** [comment]
The issue mentioned above fixed by following the instructions there https://github.com/DigitalCloud/nova-custom-views/issues/4#issuecomment-486303382.

But now, the new views has no effects at all. When I create resource index and update it like before, nothing change in the index page of that resource.

**Comment by onemoreahmad** [comment]
Ignore the issue, my bad!

**Comment by ibrahimkoujar** [comment]
Hello @onemoreahmad can you provide the solution? I am facing the same issue, the new views not working, always showing the original views.
thanks.

**Comment by onemoreahmad** [comment]
Hi @ibrahimkoujar, sorry I really can't remember what was the issue, but I think it was a silly one something has to do with composer file (?) 
I think the issue was I created a custom view for a resource with a wrong name, let's say I have a resource called "posts" and I did something like "php artisan nova:views post index", I wrote **post** not **posts**. That's why it always shows the original view because it didn't match.

Sorry really can't remember what the was issue exactly  🤦🏻‍♂️
